version: "3.9"

networks:
  monitor-net:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./config:/etc/coredns
  coredns:
    image: coredns/coredns
    expose:
      - "53/tcp"
      - "53/udp"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "10000:10000/tcp"
    volumes:
      - './config:/etc/coredns'
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
#    links:
#      - blackbox_exporter
#      - alertmanager
    volumes:
      - "./config:/config"
      - "./data/prometheus:/data"
    command: -config.file=/config/prometheus.yml -storage.local.path=/data -storage.local.retention=5000h -alertmanager.url=http://alertmanager:9093
  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    dns: 8.8.8.8
    restart: always
    volumes:
      - "./config:/config"
    command: --config.file=/config/blackbox.yml
